# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 445c433342b77370240934bead407528dd371142a2ab562b1eb3d91ab30988fbc8780c460e9da71128315af3d58a48bc6e68ec8eda8f163fc0998b4b2082a212

test:
  secret_key_base: b34bae7196fd6ca69e8ccd09c0502863c231d88cf43bb8577b8baa15101040fa91860ea72ce11629234d65bd5dc4c0689a0482b65c9736016f3b96e9faa925cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
